---
title: "Data Manipulation in R"
site: bookdown::bookdown_site
github-repo: altaf-ali/tidydata_tutorial
---

# Introduction

Data manipulation is the process of cleaning, organising and preparing data in a way that makes it suitable for analysis. Most real-world datasets require some form of manipulation to facilitate the downstream analysis and this process is often repeated a number of times during the data analysis cycle. In this workshop you will learn how to apply a consistent grammar of data manipulation to raw data and prepare it for analysis. The following topics are covered in the workshop:

- Learning to use the grammar of data manipulation
- Merging multiple datasets and creating subsets using filters 
- Reshaping data between long and wide formats 
- Summarising data with group-wise operation
- Setting up data pipelines for efficient data manipulation

This workshop is designed for individuals who are already familiar with R but wish to learn efficient techniques for data manipulation. It is recommended that you bring your own laptop with the latest version of R and RStudio installed.

----

*Last Updated: `r format(Sys.time(), "%b %d, %Y %l:%M %p")`*
